title: Master Scheduler
description: A scheduling desktop application built using Java programming language
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
repository: thanhxtruong/master-scheduler
collections:
- sections
