title: Master Scheduler
description: A scheduling desktop application built using Java programming language
show_downloads: false
google_analytics: UA-135847373-2
theme: jekyll-theme-cayman
repository: thanhxtruong/master-scheduler
