title: Master Scheduler
description: A scheduling desktop application built using Java programming language
show_downloads: false
google_analytics: UA-136158711-1
theme: jekyll-theme-cayman
repository: thanhxtruong/master-scheduler
